### ISSUE TITLE
Updating fails

### ISSUE THREAD

**Issue by EricTheMagician** [arunoda/meteor-smart-collections#2]
I cannot update an entry.

This is the code I am executing. It's embedded within a meteor method

``` javascript
    attendEvent: function(eventId){

        //make sure user is logged in
        if( !Meteor.user()){
            throw new Meteor.Error(401, "You need to login to create an event");
        }
        var email = Meteor.user().emails[0].address;
        var date = new Date().toString();

        Events.update({_id: eventId}, {$push: {attending: email}, $set: {lastUpdated:date}, $inc: {attendingCount: 1} });

        return true;
    },
```

The code above works when I enter it in the javascript console and it updates it properly. However, when I try to call it through Meteor.call, it fails with the following error

``` javascript
Your app is crashing. Here's the latest log.


/Users/ericyen/.meteorite/packages/smart-collections/arunoda/meteor-smart-collections/7603242bee01c0cc6ce63aae65bcc3f43b30bd8c/.npm/node_modules/mongodb/lib/mongodb/connection/server.js:594
        throw err;
              ^
TypeError: Cannot read property 'pendingVersions' of null
    at VersionManager.cleanVersion (app/packages/smart-collections/lib/version_manager.js:90:30)
    at processInvalidation (app/packages/smart-collections/lib/invalidator.js:228:33)
    at Cursor.each (/Users/ericyen/.meteorite/packages/smart-collections/arunoda/meteor-smart-collections/7603242bee01c0cc6ce63aae65bcc3f43b30bd8c/.npm/node_modules/mongodb/lib/mongodb/cursor.js:243:33)
    at Cursor.nextObject (/Users/ericyen/.meteorite/packages/smart-collections/arunoda/meteor-smart-collections/7603242bee01c0cc6ce63aae65bcc3f43b30bd8c/.npm/node_modules/mongodb/lib/mongodb/cursor.js:685:35)
    at Cursor.close (/Users/ericyen/.meteorite/packages/smart-collections/arunoda/meteor-smart-collections/7603242bee01c0cc6ce63aae65bcc3f43b30bd8c/.npm/node_modules/mongodb/lib/mongodb/cursor.js:899:5)
    at Cursor.nextObject (/Users/ericyen/.meteorite/packages/smart-collections/arunoda/meteor-smart-collections/7603242bee01c0cc6ce63aae65bcc3f43b30bd8c/.npm/node_modules/mongodb/lib/mongodb/cursor.js:685:17)
    at Cursor.nextObject.commandHandler (/Users/ericyen/.meteorite/packages/smart-collections/arunoda/meteor-smart-collections/7603242bee01c0cc6ce63aae65bcc3f43b30bd8c/.npm/node_modules/mongodb/lib/mongodb/cursor.js:658:14)
    at Db._executeQueryCommand (/Users/ericyen/.meteorite/packages/smart-collections/arunoda/meteor-smart-collections/7603242bee01c0cc6ce63aae65bcc3f43b30bd8c/.npm/node_modules/mongodb/lib/mongodb/db.js:1659:20)
    at g (events.js:192:14)
    at EventEmitter.emit (events.js:126:20)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

When I switch my collection back to a normal one, it works as expected.

**Comment by arunoda** [comment]
Thanks for the bug report.
Let me look at this.

**Comment by arunoda** [comment]
I just did a update. Can you check with this.

**Comment by EricTheMagician** [comment]
It fixed it.
