### ISSUE TITLE
smartcollections

### ISSUE THREAD

**Issue by musunuru** [arunoda/meteor-smart-collections#36]
hi,I downloaded the package.Can u please guide me how to run a sample  application using smart collections? using standard collection its working well

**Comment by arunoda** [comment]
Did you follow these steps: https://github.com/arunoda/meteor-smart-collections#install

What do you mean by not running? any errors? show me the error log if so.

**Comment by musunuru** [comment]
=> Meteor server running on: http://localhost:3000/
W20130926-15:55:21.084(5.5)? (STDERR) /home/560397/Downloads/meteor-smart-collections-master/leaderboard/.meteor/local/build/programs/server/boot.js:184
W20130926-15:55:21.163(5.5)? (STDERR) }).run();
W20130926-15:55:21.164(5.5)? (STDERR)    ^
W20130926-15:55:21.164(5.5)? (STDERR) TypeError: undefined is not a function
W20130926-15:55:21.164(5.5)? (STDERR)     at app/leaderboard.js:4:11
W20130926-15:55:21.164(5.5)? (STDERR)     at app/leaderboard.js:49:3
W20130926-15:55:21.164(5.5)? (STDERR)     at mains (/home/560397/Downloads/meteor-smart-collections-master/leaderboard/.meteor/local/build/programs/server/boot.js:153:10)
W20130926-15:55:21.164(5.5)? (STDERR)     at Array.forEach (native)
W20130926-15:55:21.164(5.5)? (STDERR)     at Function._.each._.forEach (/root/.meteor/tools/3cba50c44a/lib/node_modules/underscore/underscore.js:79:11)
W20130926-15:55:21.165(5.5)? (STDERR)     at /home/560397/Downloads/meteor-smart-collections-master/leaderboard/.meteor/local/build/programs/server/boot.js:80:5
=> Exited with code: 1
=> Meteor server restarted

**Comment by arunoda** [comment]
Did you install SmartCollections with

mrt add smart-collections

On Thursday, September 26, 2013, musunuru wrote:

> => Meteor server running on: http://localhost:3000/
> W20130926-15:55:21.084(5.5)? (STDERR)
> /home/560397/Downloads/meteor-smart-collections-master/leaderboard/.meteor/local/build/programs/server/boot.js:184
> W20130926-15:55:21.163(5.5)? (STDERR) }).run();
> W20130926-15:55:21.164(5.5)? (STDERR) ^
> W20130926-15:55:21.164(5.5)? (STDERR) TypeError: undefined is not a
> function
> W20130926-15:55:21.164(5.5)? (STDERR) at app/leaderboard.js:4:11
> W20130926-15:55:21.164(5.5)? (STDERR) at app/leaderboard.js:49:3
> W20130926-15:55:21.164(5.5)? (STDERR) at mains
> (/home/560397/Downloads/meteor-smart-collections-master/leaderboard/.meteor/local/build/programs/server/boot.js:153:10)
> W20130926-15:55:21.164(5.5)? (STDERR) at Array.forEach (native)
> W20130926-15:55:21.164(5.5)? (STDERR) at Function._.each._.forEach
> (/root/.meteor/tools/3cba50c44a/lib/node_modules/underscore/underscore.js:79:11)
> W20130926-15:55:21.165(5.5)? (STDERR) at
> /home/560397/Downloads/meteor-smart-collections-master/leaderboard/.meteor/local/build/programs/server/boot.js:80:5
> => Exited with code: 1
> => Meteor server restarted
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-smart-collections/issues/36#issuecomment-25157306
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by musunuru** [comment]
when i run meteor i got the follwing eror-
Sorry, this project uses Meteor 0.6.5, which is not installed and
could not be downloaded. Please check to make sure that you are online.

When i come out of smart collections package and check for version meteor --version giving Release 0.6.5.1

**Comment by arunoda** [comment]
Seems like you don't have an internet connection?

On Fri, Sep 27, 2013 at 12:57 PM, musunuru notifications@github.com wrote:

> when i run meteor i got the follwing eror-
> Sorry, this project uses Meteor 0.6.5, which is not installed and
> could not be downloaded. Please check to make sure that you are online.
> 
> When i come out of smart collections package and check for version meteor
> --version giving Release 0.6.5.1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-smart-collections/issues/36#issuecomment-25227485
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
